  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/nba_stats
      username: postgres
      password: 123456

  rapidApi:
    url: "https://api-nba-v1.p.rapidapi.com/"
    apiKey: "***"