package com.stats.nbastatsbomb.enums;

public enum TeamNames {

            ATL,
            BKN,
            BOS,
            CHA,
            CHH,
            CHI,
            CLE,
            DAL,
            DEN,
            DET,
            GSW,
            HOU,
            IND,
            LAC,
            LAL,
            MEM,
            MIA,
            MIL,
            MIN,
            NJN,
            NOH,
            NOK,
            NOP,
            NYK,
            OKC,
            ORL,
            PHI,
            PHX,
            POR,
            SAC,
            SAS,
            SEA,
            TOR,
            UTA,
            VAN,
            WAS,
}
